use_frameworks!

target 'ViewControllerHierarchy_Example' do
  pod 'ViewControllerHierarchy', :path => '../'

  target 'ViewControllerHierarchy_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
